SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE NOT REGEXP ("Spayed|Neutered") AND O.SEX_UPON_OUTCOME REGEXP ("Spayed|Neutered")
ORDER BY 1