SELECT CONVERT(DATE_FORMAT(START_DATE, "%m"), SIGNED) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (CAR_ID) IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, "%Y-%m") IN ("2022-08", "2022-09", "2022-10")
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND DATE_FORMAT(START_DATE, "%Y-%m") IN ("2022-08", "2022-09", "2022-10")
GROUP BY 1, 2
ORDER BY 1, 2 DESC