WITH RECURSIVE HH (HOUR) AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HH
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HH H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = CONVERT(DATE_FORMAT(A.DATETIME, "%HH"), SIGNED)
GROUP BY 1
ORDER BY 1