SELECT CONVERT(DATE_FORMAT(DATETIME, "%H"), SIGNED) AS HOUR , COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE CONVERT(DATE_FORMAT(DATETIME, "%H"), SIGNED) >= 9 AND CONVERT(DATE_FORMAT(DATETIME, "%H"), SIGNED) <= 19
GROUP BY 1
ORDER BY 1